<?php
$config['menu_config'] = array(
	"index"=>array
	(
		'管理中心首页',
		array
		(
			array(
				'管理中心首页',
				array(
						'info,1,admin_index,管理中心首页',  //操作内容,是否隐藏,类型名称,中文菜单名称
						'search_spuser,0,base_ajax,供应商选择窗口',
						'image_list,1,admin_index,图片管理',
						'clear_temp,1,admin_index,清空缓存',
						'web_config,1,admin_index,网站设置'
					)
				)
		)
	)
	,
	"configs"=>array
	(
		'网站管理',
		array
		(
			array(
				'权限管理',
				array(
						'group_list,1,group,权限组', 
						'group_add,1,group,添加权限组', 
						'admin_list,1,user,管理员列表',  
						'admin_add,1,user,添加管理员', 
						'admin_pwd,1,user,修改密码', 
					)
				)
		)
	)
	,
	"product"=>array
	(
		'供销管理',
		array
		(
		    array(
				'公共参数管理',
				array(
				      'cat_list,1,cat,产品类型列表', 
					  'country_list,1,country,产地管理'
					)
			),
			array(
				'供应产品管理',
				array(
				      'spuser_product,1,spuser,供应商品列表', 
					  'spuser_product_stock_check,0,spuser,审核供应商品', 
					  'spuser_list,1,spuser,供应商列表',  //按是否是接口供应商来区分如果需要开发新的接口对接 
					  'spuser_add,0,spuser,添加供应商',
					  'spuser_product_check,0,spuser,审核加入公共库'
					)
				),
		    array(
				'订阅库管理',
				array(
						'product_list,1,product,平台订阅库',  
						//'product_add,1,product,添加订阅库'
						'product_edit,0,product,编辑内容',
						'product_stock,0,product,调拨库存'
					)
				)
			,
			array(
				 '物流管理',
				  array(
						'warehouse_list,1,warehouse,仓库列表',  
						'warehouse_add,0,warehouse,添加仓库',
						'logistics_list,1,logistics,审核模板列表',  
						'logccom_list,1,logistics,物流企业列表',  
						'logccom_add,1,logistics,添加物流企业'
					)
			)
            ,
			array(
				'分销订阅管理',
				array(
					  'seller_product_list,1,seller_product,分销订阅列表', 
					  'seller_product_check,0,seller_product,上架审核操作', 
					  'seller_product_stock_check,0,seller_product,库存审核操作',
					  'seller_user_list,1,seller_user,分销用户列表',  
					  'seller_add,0,seller_user,添加分销用户'
					)
		    ),
			array(
				'订单管理',
				array(
				    'order_list_ls,1,order,零售订单',
					'order_list,1,order,批发订单',
					'sp_order_list,1,order,供应商订单',
					'order_info,0,order,订单详情',
					'order_info_1,0,order,供应商订单详情'
				)
			)
	    )
	)
	
);


